app/create_account.jsx, app/index.jsx, app/welcome.jsx, components/Button.jsx, components/Input.jsx, components/ScreamWrapper.jsx
add basic components for button and input
=> add components buttom and input

app/create_account.jsx, app/homePage.jsx, app/index.jsx, components/Button.jsx, components/Input.jsx, components/ScreamWrapper.jsx, components/TopBar.jsx, constants/Themes.js, package-lock.json, package.json
Reshaping some interfaces and components. Creation of TopBar and homePage
=> homePage and Topbar

app/index.jsx, app/test.jsx, components/SideMenu.jsx, components/TopBar.jsx, package-lock.json
Creation of SideMenu component and test interface. Changes in TopBar
=> Creation of SideMenu and test. Changes in TopBar

app/createPost_review.jsx, app/index.jsx, app/login.jsx, app/profile_user.jsx, app/searchMovies_highestRated.jsx, app/searchMovies_mostPopular.jsx, app/search_movies.jsx
Search Most Popular, 
Search Post Highest Rated
Create Post Review
- Se colocaron enlaces a algunos botones que ya tienen sus interfaces, está funcional, faltan algunos que no están implementadas las interfaces
- Se usa Themes en las interfaces para los colores
=> Se agregan interfaces y Cambios 

app/other_user_information.jsx, app/profile_information.jsx
=> add interface other_user_information 

app/index.jsx, app/movieReview.jsx, components/Header.jsx, components/Popup.jsx, constants/Themes.js
Creation of Popups and finishing movieReview. A couple changes in the Header component so the left icon could show the popups
=> Creation of Popups and finishing movieReview

app/index.jsx, app/passwordRecovery2.jsx, app/searchMovieSearch.jsx
Creation of passwordRecovery2 and searchMovieSearch
=> Creation of passwordRecovery2 and searchMovieSearch

app/index.jsx, app/searchMovieGenre.jsx, app/userPosts.jsx
Creation of interfaces searchMovieGenre and userPosts
=> Creation of searchMovieGenre and userPosts

app/change_password.jsx, app/index.jsx, app/password_recovery.jsx, app/post_tags.jsx, app/search.jsx, app/search_user.jsx
con las buenas tarde  hago avances de mis interfaces. buen dia.
=> Interfaces de Post/Tags , Search, Search User

app/index.jsx, app/movieScreen.jsx, app/myPosts.jsx
Creation of myPosts and movieScreen. I need to keep working on movieScreen, this is just the first version
=> Creation of myPosts and movieScreen

app/homePage.jsx, app/movieScreen.jsx, app/myPosts.jsx, app/test.jsx, components/Popup.jsx, components/RatingFavorite.jsx, components/SideMenu.jsx
Creation of RatingFavorite component and finishing movieReview. Implementing new component in an interface. Rerouting of homePage and fixing some issues it had
=> Creation of RatingFavorite component and finishing movieReview

app/change_password.jsx, app/index.jsx, app/password_recovery.jsx, app/post_tags.jsx, app/profile_Settings.jsx, app/profile_user.jsx, app/search.jsx
con las buenas noches realizo entrega de las correcciones de mis interfaces asignadas
=> Correcciones de las interfaces

app/addMovie.jsx, app/movieReview.jsx, app/movieScreen.jsx, app/myPosts.jsx, app/searchMovieSearch.jsx, components/Header.jsx, components/Popup.jsx, components/SideMenu.jsx
Routing a couple interfaces, creating a new constant for Popup and implementing it
=> Routing a couple interfaces and some changes for Popup

app/activity_liked_posts.jsx, app/passwordRecovery2.jsx, app/post.jsx, app/post_tags.jsx, app/search.jsx, app/search_user.jsx, components/PostComment.jsx
y enrutando activity liked post con arrowback
=> Implementando componente de Rating en Post 

app/other_user_information.jsx, app/userPosts.jsx, components/TopBar.jsx
Changes in TopBar component and routing a little bit
=> Changes in TopBar component

app/movieScreen.jsx, app/myPosts.jsx, app/other_user_information.jsx, app/searchMovieGenre.jsx
Routing more interfaces and fixing movieScreen, adding the poster/thumbnail of the movie
=> Routing more interfaces and fixing movieScreen

app/createPost_review.jsx, app/homePage_post.jsx, app/search.jsx, app/search_posts.jsx, app/welcome.jsx
=> Some statusbars and routes

app/index.jsx, app/movieScreen.jsx, app/myPosts.jsx, app/profile_information.jsx
Couple changes we did at the uni. Not a big deal
=> Changes we did at the uni

app/[movieId].jsx, app/searchMovies_highestRated.jsx, app/searchMovies_mostPopular.jsx, helpers/tmdbApi.js
Adding the movie director to [movieId].jsx and integrating the TMBD API in a couple more interfaces
=> Integrating the TMDB API in a couple more interfaces

app/homePage_post.jsx, app/movieReview.jsx, app/post.jsx, helpers/movieverseApi.js
Integration of get post by id and some validations for the movieReview interface
=> Integration of get post by id and some validations

app/search_posts.jsx, helpers/movieverseApi.js
Integrating the search post by tag endpoint
=> Integrating the search post by tag endpoint

app/homePage_post.jsx, app/movie/[movieId].jsx, app/movieReview.jsx, app/post.jsx, app/search_posts.jsx, helpers/movieverseApi.js
Integration of the endpoint to favorite movies
=> Integration of the endpoint to favorite movies

app/activity_favorite_movies.jsx, app/post.jsx, helpers/movieverseApi.js
Integration of the endpoint to see your favorite movies
=> Integration of the endpoint to see your favorite movies

app/activity_favorite_movies.jsx, helpers/movieverseApi.js
Integration of delete favorite movies endpoint
=> Integration of delete favorite movies endpoint

app/homePage_post.jsx, app/other_user_information.jsx, app/post.jsx, app/profile_user.jsx, helpers/movieverseApi.js
Integration of endpoints to see other users data
=> Integration of endpoints to see other users data

app/post.jsx, helpers/movieverseApi.js
Integration of likes endpoint in post.jsx
=> Integration of likes endpoint in post.jsx

app/movie/[movieId].jsx, helpers/movieverseApi.js
Integration of endpoint to get posts by movie id
=> Integration of endpoint to get posts by movie id

app/create_account.jsx, app/genreMovieList/[genreId].jsx, app/homePage.jsx, app/homePage_post.jsx, app/login.jsx, app/movie/[movieId].jsx, app/movieReview.jsx, app/moviesByYear/[year].jsx, app/other_user_information.jsx, app/post.jsx, app/profile_user.jsx, app/searchMovies_highestRated.jsx, app/searchMovies_mostPopular.jsx, app/search_posts.jsx, app/topMovies.jsx, components/Popup.jsx, components/SideMenu.jsx, helpers/movieverseApi.js
=> Last fixes to the front

app/create_account.jsx, app/genreMovieList/[genreId].jsx, app/homePage.jsx, app/homePage_post.jsx, app/login.jsx, app/movie/[movieId].jsx, app/movieReview.jsx, app/moviesByYear/[year].jsx, app/other_user_information.jsx, app/post.jsx, app/profile_user.jsx, app/searchMovies_highestRated.jsx, app/searchMovies_mostPopular.jsx, app/search_posts.jsx, app/topMovies.jsx, components/Popup.jsx, components/SideMenu.jsx, helpers/movieverseApi.js
Reverts IglesiasUcla/MovieVerse#74
=> Revert "Last fixes to the front"
